import pizza1 from "@/assets/images/pizza/1.png";

export const data = [
  {
    id: 0,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
  {
    id: 1,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
  {
    id: 2,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
  {
    id: 3,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
  {
    id: 4,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
  {
    id: 5,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
  {
    id: 6,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
  {
    id: 7,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
  {
    id: 8,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
  {
    id: 9,
    name: "Pepperoni",
    description:
      "A delicious pizza topped with tomato sauce, mozzarella cheese, and spicy pepperoni slices.",
    image: "https://artgallery-bucket.s3.eu-central-1.amazonaws.com/1.png",
    ingredients: ["Tomatoes", "Pepperoni", "Black Olives"],
    categories: ["Meat Lovers"],
    massSmall: 460,
    massMedium: 975,
    massLarge: 1478,
    sizeSmall: 25,
    sizeMedium: 35,
    sizeLarge: 45,
    priceSmall: 15.39,
    priceMedium: 22.65,
    priceLarge: 56.38,
  },
];
export const counter = [
  {
    id: 1,
    title: "Ingredients",
    count: 180,
  },
  {
    id: 2,
    title: "Clients Daily",
    count: 120,
  },
  {
    id: 3,
    title: "Years of Experience",
    count: 6,
  },
  {
    id: 4,
    title: "Fresh & Tasty",
    count: 120,
  },
];

export const feedback = [
  {
    id: 0,
    name: "Oksana",
    text: " id est laborum.",
    location: "Вигноградів",
    rating: 5,
    data: "21.05.2021",
  },
  {
    id: 1,
    name: "Oksana",
    text: "coolcoolcoolcool coolcool   coolcoolcool ",
    location: "Вигноградів",
    rating: 5,
    data: "21.05.2021",
  },
  {
    id: 2,
    name: "Oksana",
    text: "coolcoolcoolcool coolcool   coolcoolcool ",
    location: "Вигноградів",
    rating: 5,
    data: "21.05.2021",
  },
];

export const dataAction = [
  {
    id: 1,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 2,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 3,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 4,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 5,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 6,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 7,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 8,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 9,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 10,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 11,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 12,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
];
