import pizza1 from "@/assets/images/pizza/1.png";

export const data = [
  {
    id: 1,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
  {
    id: 2,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
  {
    id: 3,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
  {
    id: 4,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
  {
    id: 5,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
  {
    id: 6,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
  {
    id: 7,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
  {
    id: 8,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
  {
    id: 9,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
  {
    id: 10,
    image: pizza1,
    title: "Papperoni",
    price: 120,
  },
];
export const counter = [
  {
    id: 1,
    title: "Ingredients",
    count: 180,
  },
  {
    id: 2,
    title: "Clients Daily",
    count: 120,
  },
  {
    id: 3,
    title: "Years of Experience",
    count: 6,
  },
  {
    id: 4,
    title: "Fresh & Tasty",
    count: 120,
  },
];

export const feedback = [
  {
    id: 0,
    name: "Oksana",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    location: "Вигноградів",
    rating: 5,
    data: "21.05.2021",
  },
  {
    id: 1,
    name: "Oksana",
    text: "coolcoolcoolcool coolcool   coolcoolcool ",
    location: "Вигноградів",
    rating: 5,
    data: "21.05.2021",
  },
  {
    id: 2,
    name: "Oksana",
    text: "coolcoolcoolcool coolcool   coolcoolcool ",
    location: "Вигноградів",
    rating: 5,
    data: "21.05.2021",
  },
];

export const dataAction = [
  {
    id: 1,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 2,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 3,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 4,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 5,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 6,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 7,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 8,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 9,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 10,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 11,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
  {
    id: 12,
    image: pizza1,
    title: "Papperoni",
    price: 120,
    oldPrice: 30,
    ratting: 4,
  },
];
